### ISSUE TITLE
2D Arrays don't get recovered to the same format

### ISSUE THREAD

**Issue by rcnlee** [JuliaLang/JSON.jl#120]
Hello,

I would like to save a 2D array to a JSON file and then recover it later.  However, when I run:

using JSON
A = rand(5,5)
f = open("testfile.txt", "w")
JSON.print(f,A)
close(f)
f = open("testfile.txt")
B = JSON.parse(f)
close(f)

A is a 2D Array, but the recovered variable B is a Vector of Vectors.  Is this expected/intentional behavior?

Thanks,

Ritchie

**Comment by kmsquire** [comment]
This is an inherent issue with JSON, since the JSON spec does not natively support multidimensional arrays, and there's no easy way to reparse the data written as a 2D array as such.

If you're looking just to serialize and deserialize within Julia, JLD.jl would probably be a better serializer.  Otherwise, if you know that the data will be a 2D array, your best bet would be to convert the Vector of Vectors to a 2D array:

```julia
C = convert(Array{Float64,2}, hcat(B...))
```

You might need or want to do something slightly fancier, but that depends on your use case.

**Comment by kmsquire** [comment]
I'll add that the `convert` is necessary because JSON.jl doesn't attempt to figure out whether all elements in the array are the same.

**Comment by rcnlee** [comment]
Bummer, thanks for the info Kevin!

Ritchie
