### ISSUE TITLE
Downstream `_print` users

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/JSON.jl#158]
In anticipation of #151 being (hopefully) merged, the following packages are using JSON._print, which will be deprecated:

 - [x] Bokeh https://github.com/bokeh/Bokeh.jl/pull/37
 - [x] Escher https://github.com/shashi/Escher.jl/pull/173
 - [x] PlotlyJS https://github.com/spencerlyon2/PlotlyJS.jl/pull/65
 - [x] Plots https://github.com/tbreloff/Plots.jl/pull/452

(List from GitHub search.) From a quick glance, all of these packages will be easily converted to the new style. I'll submit PRs so that they can avoid the deprecation warning (but I'd like to submit that after #151 is merged and tagged).

**Comment by EricForgy** [comment]
Just FYI, I suspect this is going to hit a LOT of private repos. JSON is used by pretty much any web app. I have at least 10 private repos that will be affected.

I'm a little confused why JSON._print needs to be deprecated, but if you guys agree, I can deal with it.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Mon, Aug 8, 2016 at 10:55 AM +0800, "Fengyang Wang" <notifications@github.com<mailto:notifications@github.com>> wrote:


In anticipation of #151<https://github.com/JuliaLang/JSON.jl/pull/151> being (hopefully) merged, the following packages are using JSON._print, which will be deprecated:

  *   Bokeh
  *   Escher
  *   PlotlyJS
  *   Plots

(List from GitHub search.) From a quick glance, all of these packages will be easily converted to the new style. I'll submit PRs so that they can avoid the deprecation warning (but I'd like to submit that after #151<https://github.com/JuliaLang/JSON.jl/pull/151> is merged and tagged).

-

**Comment by TotalVerb** [comment]
The package has not been very clear about what is to be considered an internal implementation detail, but let me be frank: `JSON._print` is:

 - not documented in the README
 - preceded by an underscore

That should speak loud and clear that this is an internal function, and that it needs to be deprecated at all (as opposed to just *removed*) is unfortunate. However, I sympathize with the fact that this package did not have a good API to extend JSON serialization before. #151 fixes that, and so `JSON._print` becomes redundant and unnecessary.

This code:

```julia
JSON._print(io::IO, state::JSON.State, a::MyType) =
    JSON._print(io, state, do_something_to_convert_to_JSON_primitive(a))
```

will become

```julia
JSON.lower(a::MyType) = do_something_to_convert_to_JSON_primitive(a)
```

If your use case for `JSON._print` is similar, then the migration will be very easy. If there is any valid use of `JSON._print` that is difficult to migrate, please post on #151.

As to why the deprecation is necessary: tagging JSON v0.5.2 broke PlotlyJS, because an _internal_ function was renamed, because PlotlyJS was reimplementing the JSON serialization code. This is a bad situation that is best to avoid. Having a documented, stable API is better from the consumer's perspective.

**Comment by TotalVerb** [comment]
All four PRs have been merged.
